name: Run Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12, 14, 16]
    steps:
      - name: Pull repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.22.2
      - name: Run tests
        run: pnpm test
